### ISSUE TITLE
Hi.  I have a question.

### ISSUE THREAD

**Issue by jaha0308** [sonnyhcl/PYNQ-Light-Cube#1]
I am interested in the PYNQ board and want to control the lightcube.

I want to ask a question about lightcube.

Does it matter what lightcube you can buy on eBay or AliExpress?

I have Led cube for Arduino but this doesn't support usb port.

I'm a low grade electronics student, so I'm sorry for the lack

I really want to answer your questions

**Comment by sonnyhcl** [comment]
This cube used in this repo is a self-built one and it doesn't have any drivers like usb or whatever. We wrote a simple "driver" in FPGA part to light LED. There is no any ready-made part in ebay or aliexpress.
